{{ if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-api
              servicePort: api
            path: /studio-api/?(.*)
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-ui
  annotations:
  #    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-ui
              servicePort: ui
            path: /
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-ws
  annotations:
    ingress.kubernetes.io/proxy-connect-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-ws
              servicePort: ws
            path: /ws/?(.*)
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
