# The Enketo conf needs to be a Secret because it includes passwords
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  # For now, you must set ENKETO_API_TOKEN, used by KPI and KoBoCAT, to the same
  # value as ENKETO_API_KEY. Eventually, KPI and KoBoCAT will also read
  # ENKETO_API_KEY and the duplication will no longer be necessary.
  #  For a description of this setting, see "api key" here:
  #  https://github.com/kobotoolbox/enketo-express/tree/master/config#linked-form-and-data-server.
  ENKETO_API_KEY: {{ .Values.enketo.apiKey | b64enc | quote }}
  ENKETO_API_TOKEN: {{ .Values.enketo.apiKey | b64enc | quote }}
  ENKETO_LINKED_FORM_AND_DATA_SERVER_API_KEY: {{ .Values.enketo.apiKey | b64enc | quote }}
  ENKETO_ENCRYPTION_KEY: {{ .Values.enketo.encryptionKey | b64enc | quote }}

  # Canonically a 50-character random string. For Django 1.8.13, see https://docs.djangoproject.com/en/1.8/ref/settings/#secret-key and https://github.com/django/django/blob/4022b2c306e88a4ab7f80507e736ce7ac7d01186/django/core/management/commands/startproject.py#L29-L31.
  # To generate a secret key in the same way as `django-admin startproject` you can run:
  # docker-compose run --rm kpi python -c 'from django.utils.crypto import get_random_string; print(get_random_string(50, "abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)"))'
  DJANGO_SECRET_KEY: {{ .Values.general.djangoSecret | b64enc | quote }}

  KOBO_SUPERUSER_PASSWORD: {{ .Values.general.superUser.password | b64enc | quote }}

  # Mongo Passwords
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  KOBO_MONGO_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  KOBOCAT_MONGO_PASS: {{ .Values.mongodb.auth.password | b64enc | quote }}
  KPI_MONGO_PASS: {{ .Values.mongodb.auth.password | b64enc | quote }}

  postgresPostgresPassword: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}

  KC_DATABASE_URL: {{ include "kc_dburl" . | b64enc | quote }}

  KPI_DATABASE_URL: {{ include "kpi_dburl" . | b64enc | quote }}
  KPI_URL: {{ include "kpi_dburl" . | b64enc | quote }}

  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}

  REDIS_PASSWORD: {{ .Values.global.redis.password | b64enc | quote }}
  REDIS_SESSION_URL: {{ include "redis_url_session" . | b64enc | quote }}
  REDIS_LOCK_URL: {{ include "redis_url_lock" . | b64enc | quote }}
  KOBOCAT_BROKER_URL: {{ include "redis_url_kobobroker" . | b64enc | quote }}
  KPI_BROKER_URL: {{ include "redis_url_kpibroker" . | b64enc | quote }}
