apiVersion: v1
kind: Service
metadata:
  name: fineract-activemq-svc
  labels:
    app: fineract-activemq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    name: amqp
    targetPort: 5672
    protocol: TCP
  - port: 61616
    targetPort: 61616
    name: openwire
    protocol: TCP
  selector:
    app: fineract-activemq
---
apiVersion: v1
kind: Service
metadata:
  name: fineract-activemq-web-console
  labels:
    app: fineract-activemq
spec:
  type: ClusterIP
  ports:
  - port: 8161
    targetPort: 8161
    name: web-console
    protocol: TCP
  selector:
    app: fineract-activemq
