{{ if .Values.fineractrest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fineract.rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fineract-rest
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8443
  selector:
    app: fineract-rest
    tier: backend
    nstance: {{ .Release.Name }}
{{- end -}}
