{{ if .Values.fineractjob.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fineract.job.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fineract-job
    tier: backend
spec:
  selector:
    matchLabels:
      app: fineract-job
      tier: backend
      instance: {{ .Release.Name }}
  replicas: {{ .Values.fineractjob.replicaCount }}
  serviceName: fineract-job
  template:
    metadata:
      labels:
        app: fineract-job
        tier: backend
        instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
          - -wait
          - tcp://{{ include "mysql_host" . }}:3306
          - -timeout
          - 300s
      containers:
        - name: fineract-job
          image: "{{ .Values.fineract_backend.image.name }}:{{ .Values.fineract_backend.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy}}
          ports:
            - name: job-port
              containerPort: 8443
            - name: http
              containerPort: 8080
          env:
            - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
              value: {{ include "mysql_host" . }}
            - name: FINERACT_DEFAULT_TENANTDB_UID
              value: {{ include "mysql_user" . }}
            - name: FINERACT_DEFAULT_TENANTDB_PWD
              value: {{ .Values.mysql.auth.password | quote }}
            - name: fineract_tenants_uid
              value: {{ include "mysql_user" . }}
            - name: fineract_tenants_pwd
              value: {{ .Values.mysql.auth.password | quote }}
            - name: fineract_tenants_url
              value: "jdbc:mysql://{{ include "mysql_host" . }}:3306/{{ .Values.global.db.tenantsDb }}"
            - name: FINERACT_DEFAULT_TENANTDB_PORT
              value: "{{ .Values.global.db.FINERACT_DEFAULT_TENANTDB_PORT }}"
            - name: fineract.allowJobs
              value: "true"
          args:
            - sh
            - -c
            - java -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true --illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED -jar fineract-provider.jar --spring.profiles.active=basicauth
          readinessProbe:
            httpGet:
              path: /fineract-provider/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /fineract-provider/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 10
          volumeMounts:
            - name: fineract-job
              mountPath: /opt/fineract/logs
          resources:
            {{- .Values.fineractjob.resources | toYaml | nindent 12 }}
      volumes:
        - name: fineract-job
          persistentVolumeClaim:
            claimName: fineract-job-pvc
{{- end -}}
