global:
  # -- This will be used on all pods for all PVCs, including dependencies (postgres)
  storageClass: standard

general:
  # -- Used for all published services
  serviceType: ClusterIP

# -- See https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html for more details
metabase:
  # -- Replica count
  replicas: 1
  image:
    # -- Metabase image name
    name: metabase/metabase
    # -- Metabase image tag
    tag: latest
  # -- Array of URLs to download extra plugins from (jar files)
  extraPlugins: []

# -- Postgres config
# See https://artifacthub.io/packages/helm/bitnami/postgresql for docs
postgresql:
  # -- Install postgres?
  enabled: true
  # Specify an external host here if desired - otherwise we will use the subchart dependency
  host: ''

  # -- Password for the `postgres` user
  postgresqlPostgresPassword: H55Djpc7Vs
  # -- Database to create and use
  postgresqlDatabase: metabase
  # -- Application username
  postgresqlUsername: metabase
  # -- Application password
  postgresqlPassword: ciJ8KfiMUK
  service:
    # -- Postgres port
    port: 5432
