apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fineract-report-pvc
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  accessModes:
    - {{ .Values.accessModes | quote }}
  resources:
    requests:
      storage: 5Gi
