apiVersion: v2
name: flagsmith
version: 0.1.1
description: Flagsmith - a Feature flag and remote configuration solution
type: application
icon: https://avatars.githubusercontent.com/u/58150233?s=400&v=4
home: https://flagsmith.com/
keywords:
  - feature-flags
  - remote-config
sources:
  - https://github.com/one-acre-fund/oaf-public-charts/tree/main/charts/flagsmith
maintainers:
  - name: Yann-J
    email: yann.jouanique@gmail.com
dependencies:
  - name: postgresql
    version: ~10.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
