{{- if .Values.extraSecretEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.fullname" . }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.extraSecretEnvs }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
